
panda_gripper_controller:
  type: effort_controllers/JointGroupPositionController
  joints:
      - panda_finger_joint1
      - panda_finger_joint2
  panda_finger_joint1:
    pid: {p: 5000,  i: 50, d: 0.5}
  panda_finger_joint2:
    pid: {p: 5000,  i: 50, d: 0.5}
